# Generated by Django 3.2.5 on 2021-07-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='A stock-keeping unit (SKU) is a scannable bar code, most often seen printed on product labels in a retail store.', max_length=12, unique=True, verbose_name='SKU'),
        ),
    ]
